apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: post-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: post.com
      http:
        paths:
          - path: /post
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip
                port:
                  number: 4000
