apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: naveedalirehmani/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: '.'
